// <auto-generated />
namespace Rm_Midterm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CourseStatusTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CourseStatusTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202111191835416_CourseStatusTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
